version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    networks:
      - backend-network

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
    ports:
      - '8081:8081'
    networks:
      - backend-network

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - '6379:6379'
    networks:
      - backend-network
      
  backend:
    build: .
    container_name: backend-whatsapp-de-wish
    depends_on:
      - mongo
      - redis
    ports:
      - '3000:3000'
    networks:
      - backend-network
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

networks:
  backend-network:
    driver: bridge
    attachable: true
